import { ErrorMap } from '../types';
import { z } from 'zod';

export function extractValidationErrors(error: Error): ErrorMap[] {
  // Extract and format validation errors from the error object
  let validationErrors: ErrorMap[] = [];

  if (error instanceof z.ZodError) {
    // If the error is a ZodError (generated by Zod validation)
    validationErrors = error.errors.map((err) => ({
      field: err.path.join('.'),
      message: err.message,
    }));
  } else {
    // This Handles other types of errors
    validationErrors.push({ field: '', message: 'something went wrong' });
  }

  return validationErrors;
}
